const sql = require("mssql");

const allowedMailAttributes = {
  nRepairNumber: sql.Int,
  nHitPoint: sql.Int,
  nMaxHitPoint: sql.Int,
  nMaterial: sql.Int,
  byFlag: sql.Int,
  dwSerialNumber: sql.Int,
  nOption: sql.Int,
  bItemResist: sql.Int,
  nResistAbilityOption: sql.Int,
  idGuild: sql.Int,
  nResistSMItemId: sql.Int,
  bCharged: sql.Int,
  dwKeepTime: sql.Int,
  nRandomOptItemId: sql.BigInt,
  nPiercedSize: sql.Int,
  dwItemId1: sql.Int,
  dwItemId2: sql.Int,
  dwItemId3: sql.Int,
  dwItemId4: sql.Int,
  bPet: sql.Int,
  nKind: sql.Int,
  nLevel: sql.Int,
  dwExp: sql.Int,
  wEnergy: sql.Int,
  wLife: sql.Int,
  anAvailLevel_D: sql.Int,
  anAvailLevel_C: sql.Int,
  anAvailLevel_B: sql.Int,
  anAvailLevel_A: sql.Int,
  anAvailLevel_S: sql.Int,
  dwItemId5: sql.Int,
  dwItemId6: sql.Int,
  dwItemId7: sql.Int,
  dwItemId8: sql.Int,
  dwItemId9: sql.Int,
  dwItemId10: sql.Int,
  dwItemId11: sql.Int,
  dwItemId12: sql.Int,
  dwItemId13: sql.Int,
  dwItemId14: sql.Int,
  dwItemId15: sql.Int,
  nPiercedSize2: sql.Int,
  szPetName: sql.VarChar,
};

module.exports = allowedMailAttributes;
